config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "welcome#index"
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true
  
  def self.new_lookup(ticker_symbol)
    ticker_symbol.upcase!
    api_key = Rails.application.credentials.binance[:api_key]
    api_secret = Rails.application.credentials.binance[:secret_key]
    begin
      client = Binance::Client::REST.new api_key: api_key, secret_key: api_secret
      price = client.price(symbol: ticker_symbol)['price'].to_f
      new(ticker: ticker_symbol, name: ticker_symbol, last_price: price)
    rescue => exception
      return nil      
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def can_track_stock?(ticker_symbol)
    under_stock_limit? and not stock_already_tracked?(ticker_symbol)
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name or last_name
    "Anonymous"
  end

  def self.search(name)
    name.strip!
    where("first_name LIKE ? OR last_name LIKE ? OR email LIKE ?", "%#{name}%", "%#{name}%", "%#{name}%")
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    friend = User.find(params[:friend])
    current_user.friends << friend
    flash[:notice] = 'Following friend'
    redirect_to my_friends_path
  end

  def destroy
    friend = User.find(params[:id])
    friendship = Friendship.where(user_id: current_user.id, friend_id: friend.id).first.destroy
    flash[:notice] = "You stopped following #{friend.full_name}"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        if @stock.last_price == 0
          respond_to do |format|
            @stock = nil
            flash.now[:alert] = 'No such symbol'
            format.js { render partial: 'users/result_js' }
          end
        else
          respond_to do |format|
            format.js { render partial: 'users/result_js' }
          end
        end
      else
        respond_to do |format|
          flash.now[:alert] = 'Cannot connect to binance server'
          format.js { render partial: 'users/result_js' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter a symbol to search'
        format.js { render partial: 'users/result_js' }
      end
    end
  end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was succesfully added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    UserStock.where(user_id: current_user.id, stock_id: params[:id]).first.destroy
    flash[:notice] = "#{stock.ticker} was successfully removed from your portfolio"
    redirect_to my_portfolio_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @my_friends = current_user.friends
  end

  def search
    if params[:friend].present?
      @my_friends = User.search(params[:friend])
      @my_friends = @my_friends.to_a
      @my_friends.delete(current_user)
      if @my_friends.count == 0
        respond_to do |format|
          flash.now[:alert] = '0 people found'
          format.js { render partial: 'friends/search_js' }
        end
      else
        respond_to do |format|
          format.js { render partial: 'friends/search_js' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter a name to search'
        format.js { render partial: 'friends/search_js' }
      end
    end

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list.html.erb
<% if !@my_friends.empty? %>
  <div class='row'>
    <div class='col-9'>
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Full Name</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @my_friends.each do |friend| %>
            <tr>
              <td><%= friend.full_name %></td>
              <td>
                <%= link_to 'View Profile', user_path(friend), class: 'btn btn-xs btn-success' %>
                <%= link_to 'Stop following', friendship_path(friend), method: :delete, data: {confirm: 'Are you sure'}, class: 'btn btn-xs btn-warning' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/friends/_search.html.erb
<div class='results-block'>
  <%= render 'layouts/messages' %>
</div>

<% if @my_friends %>
  <% @my_friends.each do |friend| %>
    <div class='row'>
      <div class='card card-header results-block'>
        <strong>Name: </strong> <%= friend.full_name %>
        <strong>Profile: </strong> <%= link_to 'View profile', user_path(friend), class: 'btn btn-xs btn-success' %>
        <% if not current_user.friends.include? friend %>
          <%= link_to 'Follow', friendships_path(friend: friend), class: 'btn btn-xs btn-success', method: :post %>
        <% else %>
          <span class='badge bg-secondary'>
            is your friend
          </span>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/friends/_search_js.js.erb
$('#results').html("<%= j render 'friends/search' %>")

app/views/layouts/_messages.html.erb
<% unless notice.nil? %>
	<div class='alert alert-success alert-dismissible fade show' role="alert">
		<%= notice %>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
<% end %>
<% unless alert.nil? %>
	<div class='alert alert-danger alert-dismissible fade show' role="alert">
		<%= alert %>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid container">
    <%= link_to 'Finance Tracker', root_path, class: 'navbar-brand' %>
    <% if current_user %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <% my_portfolio_path_link_class = 'nav-link ' %>
            <% my_portfolio_path_link_class += 'active' if request.path == my_portfolio_path %>
            <%= link_to 'My Portfolio', my_portfolio_path, class: my_portfolio_path_link_class %>
          </li>
          <li class="nav-item">
            <% my_friends_path_link_class = 'nav-link ' %>
            <% my_friends_path_link_class += 'active' if request.path == my_portfolio_path %>
            <%= link_to 'My Friends', my_friends_path, class: my_friends_path_link_class %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                  <%= fa_icon 'edit' %> Edit Profile
                <% end %>
              </li>
            </ul>
          </li>
        </ul>
        <ul class='navbar-nav ml-auto'>
          <li class='nav-item'>
            <div class='nav-link'>Hello, <%= fa_icon 'user' %> <%= current_user.full_name %></div>
          </li>
          <li class='nav-item'>
            <%= link_to 'Logout', destroy_user_session_path, class: 'btn btn-xs btn-danger logout-button', method: :delete %>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class='container'>
      <br>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<% if !@tracked_stocks.empty? %>
  <div class='row'>
    <div class='col-9'>
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @tracked_stocks.each do |stock| %>
            <tr>
              <th scope="row"><%= stock.ticker %></th>
              <td><%= stock.name %></td>
              <td><%= stock.last_price %></td>
              <td>
                <% if current_user.id == @user.id %>
                  <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: 'Are you sure'}, class: 'btn btn-xs btn-warning' %>
                <% else %>
                  <% if current_user.can_track_stock?(stock.ticker) %>
                    <%= link_to 'Add To Portfolio', user_stocks_path(user: current_user, ticker: stock.ticker), class: 'btn btn-xs btn-success', method: :post %>
                  <% elsif current_user.id != @user.id %>
                    <span class='badge bg-secondary'>
                      You are already tracking
                      <% if not current_user.under_stock_limit? %>
                        10 cryptos
                      <% end %>
                      <% if current_user.stock_already_tracked?(stock.ticker) %>
                        this crypto
                      <% end %>
                    </span>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/users/_result.html.erb
<div class='results-block'>
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
  <div class='card card-header results-block'>
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add To Portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), class: 'btn btn-xs btn-success', method: :post %>
    <% else %>
      <span class='badge bg-secondary'>
        You are already tracking
        <% if not current_user.under_stock_limit? %>
          10 cryptos
        <% end %>
        <% if current_user.stock_already_tracked?(@stock.ticker) %>
          this crypto
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result_js.js.erb
$('#results').html("<%= j render 'users/result' %>")

app/views/users/my_friends.html.erb
<h1>My Friends</h1>

<div class='search-area'>
  <h3>Search Friends</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class='form-group row'>
      <div class='col-sm-9 no-right-padding'>
        <%= text_field_tag :friend, params[:friend], autofocus: true, class: 'form-control form-control-lg' %>
      </div>
      <div class='col-sm-3'>
        <%= button_tag type: :submit, class: 'btn btn-success' do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id='results' class='container'></div>

<%= render 'friends/list' %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class='search-area'>
  <h3>Search Stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class='form-group row'>
      <div class='col-sm-9 no-right-padding'>
        <%= text_field_tag :stock, params[:stock], placeholder: 'Symbol', autofocus: true, class: 'form-control form-control-lg' %>
      </div>
      <div class='col-sm-3'>
        <%= button_tag type: :submit, class: 'btn btn-success' do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<br>

<div id='results'></div>

<%= render 'stocks/list' %>

app/views/users/show.html.erb
<h2>User Details</h2>

<div class='row'>
  <div class='card card-header results-block'>
    <strong>Name: </strong> <%= @user.full_name %>
    <% if not current_user.friends.include? @user %>
      <%= link_to 'Follow', friendships_path(friend: @user), class: 'btn btn-xs btn-success', method: :post %>
    <% else %>
      <span class='badge bg-secondary'>
        is your friend
      </span>
    <% end %>
  </div>
</div>

<% if not @tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% else %>
  <p class='lead'>This user is not tracking cryptos</p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to the Finance Tracker App</h1>

<%= link_to 'Sign out', destroy_user_session_path %>